import { CampoCatalogo } from './config-conferencia.model';

/**
 * Catálogo estático dos 55 campos nativos da TGFCCO — rótulo, aba/sub-seção, tipo de
 * controle, dependências, e o status de implementação (resultado de auditoria real contra
 * `separacao/` e `conferencia/` nesta sessão — arquivos citados em cada `statusObservacao`).
 *
 * Vive só no frontend de propósito — é metadado de EXIBIÇÃO, não dado de negócio; o backend
 * só sincroniza os valores crus (`campos: Record<string,string>`). A Fase 2 (edição/write-back)
 * reaproveita esta mesma estrutura pra validar o que pode ser editado.
 */
export const CATALOGO_CONFIG_CONFERENCIA: CampoCatalogo[] = [
  // ─── Aba Geral — Bloco principal ─────────────────────────────────────────
  {
    nome: 'MOMENTOCONFERENCIA',
    label: 'Momento da conferência',
    aba: 'geral',
    subSecao: 'Bloco principal',
    controle: 'select',
    opcoes: [
      { valor: 'C', label: 'Antes da confirmação' },
      { valor: 'F', label: 'Antes de faturar' },
    ],
    descricao: 'Define se a conferência é exigida antes de confirmar o documento, ou antes de faturar.',
    status: 'nao_implementado',
    statusObservacao: 'SeparacaoService.iniciar sempre abre a conferência na hora, sem distinguir confirmação vs. faturamento.',
  },
  {
    nome: 'BUSCARCODBARRAPOR',
    label: 'Buscar código de barras por',
    aba: 'geral',
    subSecao: 'Bloco principal',
    controle: 'select',
    opcoes: [
      { valor: 'A', label: 'Automático' },
      { valor: 'C', label: 'Código do produto' },
      { valor: 'E', label: 'Estoque' },
      { valor: 'R', label: 'Referência' },
      { valor: 'U', label: 'Unidade alternativa' },
    ],
    descricao: 'Define em qual campo do cadastro do produto o sistema busca ao ler um código de barras.',
    status: 'parcial',
    statusObservacao: 'Lido/cacheado (ConfigConferenciaCache.kt) e usado em SeparacaoRepository.resolverContra (modos A/C/R/U/E), mas cadeia de fallback mais simples que a nativa.',
  },
  {
    nome: 'TIPOCONTAGEM',
    label: 'Tipo de contagem',
    aba: 'geral',
    subSecao: 'Bloco principal',
    controle: 'select',
    opcoes: [
      { valor: 'C', label: 'Contagem cumulativa' },
      { valor: 'P', label: 'Contagem única por produto' },
      { valor: 'Q', label: 'Contagem cumulativa com qtd.' },
    ],
    descricao: 'Cumulativa: cada bipe soma 1. Única: pede quantidade uma vez. Cumulativa c/ qtd: soma quantidade a cada bipe.',
    status: 'nao_implementado',
    statusObservacao: 'Não existe distinção de modo de contagem — só conferirItem/devolverItem, sem essa configuração.',
  },
  {
    nome: 'EXPLODIRLOTE',
    label: 'Detalhar lote pela conferência',
    aba: 'geral',
    subSecao: 'Bloco principal',
    controle: 'toggle',
    descricao: 'Permite que o lote do produto seja determinado durante a conferência (só documentos de saída).',
    status: 'nao_implementado',
    statusObservacao: 'identificarProduto monta lista de controles existentes, mas não "explode" quantidade por lote durante a conferência.',
  },

  // ─── Aba Geral — Regras gerais ────────────────────────────────────────────
  {
    nome: 'CONFPORSERIE',
    label: 'Conferência por série',
    aba: 'geral',
    subSecao: 'Regras gerais',
    controle: 'toggle',
    descricao: 'Captura número de série do produto durante a conferência, para produtos controlados por série.',
    status: 'nao_implementado',
    statusObservacao: 'SeparacaoTables.kt só tem coluna `controle` (lote) — nenhum campo de número de série.',
  },
  {
    nome: 'IGNORACOMPONENTKIT',
    label: 'Ignorar componentes de Kit',
    aba: 'geral',
    subSecao: 'Regras gerais',
    controle: 'toggle',
    descricao: 'Componentes de um Kit não aparecem na grade; conferência é feita só pelo código de barras do Kit.',
    status: 'nao_implementado',
    statusObservacao: 'Nenhuma informação de kit/componente é carregada em SeparacaoService — sem lógica de expansão de kit.',
  },
  {
    nome: 'EXIGEIDENTIFPROD',
    label: 'Exige identificador do produto',
    aba: 'geral',
    subSecao: 'Regras gerais',
    controle: 'select',
    opcoes: [
      { valor: 'N', label: 'Não exige' },
      { valor: 'O', label: 'Exige todos (opcionalmente)' },
      { valor: 'T', label: 'Exige todos' },
      { valor: 'U', label: 'Exige um' },
    ],
    descricao: 'Controla se a conferência pede identificador(es) adicional(is) do produto, e com que obrigatoriedade.',
    status: 'parcial',
    statusObservacao: 'oq-scan-bar.component.ts sempre exige identificar antes de conferir — fluxo fixo, não controlado por essa config.',
  },
  {
    nome: 'PROIBEALTERARDOCUMENTO',
    label: 'Proibe alt. documento em conferência',
    aba: 'geral',
    subSecao: 'Regras gerais',
    controle: 'toggle',
    descricao: 'Bloqueia alteração de quantidade/itens do documento enquanto a conferência está em andamento.',
    status: 'nao_implementado',
    statusObservacao: 'Não existe tela/rota de edição de documento na conferência — nada a proibir, e sem checagem desse flag.',
  },
  {
    nome: 'ABRIRCONFERENCIA',
    label: 'Abrir Fila de Conferência ao faturar',
    aba: 'geral',
    subSecao: 'Regras gerais',
    controle: 'toggle',
    descricao: 'Só habilitado quando Momento da Conferência = "Antes de faturar". Abre a Fila automaticamente ao faturar.',
    status: 'nao_aplicavel',
    statusObservacao: 'Refere-se a abrir a tela nativa "Fila de Conferência" ao faturar no Sankhya — não existe conceito equivalente no fluxo daqui.',
    dependeDe: ['MOMENTOCONFERENCIA'],
    condicao: (v) => v['MOMENTOCONFERENCIA'] === 'F',
  },

  // ─── Aba Geral — Comportamento da interface ──────────────────────────────
  {
    nome: 'EXIBIRPROD',
    label: 'Exibir produtos do pedido',
    aba: 'geral',
    subSecao: 'Comportamento da interface',
    controle: 'toggle',
    descricao: 'Mostra painel com grade dos produtos negociados no documento.',
    status: 'implementado',
    statusObservacao: 'Snapshot na sessão (V28) → SessaoSeparacao.exibirProd; conferencia.component esconde o painel de pendentes quando = "N".',
  },
  {
    nome: 'EXIBIRQTD',
    label: 'Exibir quantidade do pedido',
    aba: 'geral',
    subSecao: 'Comportamento da interface',
    controle: 'toggle',
    descricao: '(depende de Exibir produtos) Mostra coluna "Quantidade Negociada" na grade de itens.',
    status: 'implementado',
    statusObservacao: 'Snapshot na sessão (V28) → SessaoSeparacao.exibirQtd; oq-pending-list esconde a coluna de quantidade quando = "N".',
    dependeDe: ['EXIBIRPROD'],
    condicao: (v) => v['EXIBIRPROD'] === 'S',
  },
  {
    nome: 'EXIBIRCODBARRAS',
    label: 'Exibe código de barras dos produtos do pedido',
    aba: 'geral',
    subSecao: 'Comportamento da interface',
    controle: 'select',
    opcoes: [
      { valor: 'A', label: 'Automático' },
      { valor: 'C', label: 'Aba Códigos de barra do cadastro' },
      { valor: 'N', label: 'Não exibir' },
    ],
    descricao: '(depende de Exibir produtos) Mostra coluna de código de barras na grade.',
    status: 'nao_implementado',
    statusObservacao: 'ConferenciaItem guarda `code` (=codprod), não o código de barras bipado/associado — nenhum componente exibe isso.',
    dependeDe: ['EXIBIRPROD'],
    condicao: (v) => v['EXIBIRPROD'] === 'S',
  },
  {
    nome: 'EXIBIRPRODCONF',
    label: 'Exibir produtos conferidos',
    aba: 'geral',
    subSecao: 'Comportamento da interface',
    controle: 'toggle',
    descricao: 'Mostra painel com os produtos já conferidos.',
    status: 'implementado',
    statusObservacao: 'Snapshot na sessão (V28) → SessaoSeparacao.exibirProdConf; conferencia.component esconde o painel de conferidos quando = "N".',
  },
  {
    nome: 'EXIBIRQTDCONF',
    label: 'Exibir quantidade conferida',
    aba: 'geral',
    subSecao: 'Comportamento da interface',
    controle: 'toggle',
    descricao: '(depende de Exibir produtos conferidos) Mostra coluna de quantidade conferida.',
    status: 'implementado',
    statusObservacao: 'Snapshot na sessão (V28) → SessaoSeparacao.exibirQtdConf; oq-conferred-list e a tarja de última leitura escondem a quantidade quando = "N".',
    dependeDe: ['EXIBIRPRODCONF'],
    condicao: (v) => v['EXIBIRPRODCONF'] === 'S',
  },
  {
    nome: 'FEEDBACKAUTOMATICO',
    label: 'Exibir divergências ao conferir',
    aba: 'geral',
    subSecao: 'Comportamento da interface',
    controle: 'toggle',
    descricao: 'Liga automaticamente EXIBIRPRODCONF, EXIBIRQTDCONF, EXIBIRPROD e EXIBIRQTD ao ativar.',
    status: 'parcial',
    statusObservacao: 'EXIBIRPROD/EXIBIRQTD/EXIBIRPRODCONF/EXIBIRQTDCONF agora são respeitados individualmente (V28); o Sankhya já resolve o cascata deste toggle nesses campos. Falta só o alerta sonoro (EXIBIRALERTASONORO).',
    dependeDe: ['EXIBIRPRODCONF', 'EXIBIRQTDCONF', 'EXIBIRPROD', 'EXIBIRQTD'],
  },
  {
    nome: 'EXIBIRIMGPROD',
    label: 'Exibir imagem do produto',
    aba: 'geral',
    subSecao: 'Comportamento da interface',
    controle: 'toggle',
    descricao: 'Mostra imagem cadastrada do produto durante a conferência.',
    status: 'implementado',
    statusObservacao: 'ProdutoImagemService + lastScan.imagemUrl exibem a foto; snapshot na sessão (V28) → SessaoSeparacao.exibirImgProd esconde o painel de última leitura quando = "N".',
  },
  {
    nome: 'EXIBIRALERTASONORO',
    label: 'Emitir alerta sonoro em mensagens de divergência',
    aba: 'geral',
    subSecao: 'Comportamento da interface',
    controle: 'toggle',
    descricao: 'Toca um som ao detectar divergência.',
    status: 'nao_implementado',
    statusObservacao: 'Nenhum áudio/beep existe em qualquer componente do módulo conferência.',
  },
  {
    nome: 'IGNORAMSGCONF',
    label: 'Inibir mensagem de confirmação ao finalizar conferência',
    aba: 'geral',
    subSecao: 'Comportamento da interface',
    controle: 'toggle',
    descricao: 'Suprime a mensagem de confirmação ao concluir a conferência.',
    status: 'nao_implementado',
    statusObservacao: 'Não há diálogos/mensagens de confirmação no fluxo — nada a suprimir.',
  },

  // ─── Aba Geral — Faturamento/Confirmação ─────────────────────────────────
  {
    nome: 'MULTENTREGAS',
    label: 'Aceita múltiplas entregas',
    aba: 'geral',
    subSecao: 'Faturamento/Confirmação',
    controle: 'toggle',
    descricao: '(só com Momento = "Antes de faturar") Permite finalizar conferência parcial e liberar o restante depois.',
    status: 'nao_implementado',
    statusObservacao: 'Sem tratamento de entregas parciais — só QTDNEG/QTDENTREGUE simples em SeparacaoTables.kt.',
    dependeDe: ['MOMENTOCONFERENCIA'],
    condicao: (v) => v['MOMENTOCONFERENCIA'] === 'F',
  },
  {
    nome: 'CONSIDERAESTCONF',
    label: 'Ao faturar, considerar estoque conferido',
    aba: 'geral',
    subSecao: 'Faturamento/Confirmação',
    controle: 'toggle',
    descricao: 'Usa a quantidade conferida no faturamento, mesmo sem estoque disponível. Risco documentado de distorção de custo/kardex.',
    status: 'parcial',
    statusObservacao: 'TGFEST é consultado pra resolução de código de barras (SeparacaoService), mas não há validação/reserva de estoque no faturamento (que nem existe aqui).',
  },
  {
    nome: 'FATAOCONCLUIR',
    label: 'Faturar ao concluir conferência',
    aba: 'geral',
    subSecao: 'Faturamento/Confirmação',
    controle: 'toggle',
    descricao: 'Ao finalizar a conferência com sucesso, dispara faturamento automático.',
    status: 'nao_implementado',
    statusObservacao: 'Nenhuma chamada de faturamento existe — onConfirmar() no frontend só faz console.log (write-back é stub).',
  },
  {
    nome: 'ABRIRNOTAFAT',
    label: 'Abrir nota faturada na finalização da conferência',
    aba: 'geral',
    subSecao: 'Faturamento/Confirmação',
    controle: 'toggle',
    descricao: 'Após faturamento automático, abre a Central de Vendas já na nota gerada.',
    status: 'nao_aplicavel',
    statusObservacao: 'Não há navegação para tela de nota fiscal/central de vendas neste projeto.',
  },
  {
    nome: 'SOLRECNOCORTE',
    label: 'Ao efetuar corte pela Central/Portal',
    aba: 'geral',
    subSecao: 'Faturamento/Confirmação',
    controle: 'select',
    opcoes: [
      { valor: 'N', label: 'Não exigir' },
      { valor: 'S', label: 'Exigir recontagem de produtos cortados' },
    ],
    descricao: 'Define se um corte feito fora da tela de Conferência força recontagem automática.',
    status: 'nao_implementado',
    statusObservacao: 'Sem qualquer lógica de "corte" implementada (ver aba Corte/Divergência) nem de recontagem associada.',
  },

  // ─── Aba Geral — Produtos controlados por lote ───────────────────────────
  {
    nome: 'USASEQCODBAR',
    label: 'Usar seq. lote no cód. barras',
    aba: 'geral',
    subSecao: 'Produtos controlados por lote',
    controle: 'toggle',
    descricao: 'Código de barras no formato <CODBARRAS><SEPARADOR><SEQUENCIA>, rastreando unidades exatas de um lote.',
    status: 'nao_implementado',
    statusObservacao: 'Nenhum sequenciador de código de barras existe em SeparacaoTables.kt/SeparacaoRepository.kt.',
  },
  {
    nome: 'SEPSEQCODBAR',
    label: 'Separador',
    aba: 'geral',
    subSecao: 'Produtos controlados por lote',
    controle: 'texto',
    descricao: 'Caractere separador usado no formato de sequência de lote.',
    status: 'nao_implementado',
    statusObservacao: 'Depende de USASEQCODBAR, que não existe.',
    dependeDe: ['USASEQCODBAR'],
    condicao: (v) => v['USASEQCODBAR'] === 'S',
  },
  {
    nome: 'VALLOTCONEST',
    label: 'Valida lote conforme Estoque',
    aba: 'geral',
    subSecao: 'Produtos controlados por lote',
    controle: 'toggle',
    descricao: '(depende de Detalhar lote) Verifica se o lote informado existe de fato no estoque durante a bipagem.',
    status: 'nao_implementado',
    statusObservacao: 'resolverContra resolve contra o estoque, mas não valida explicitamente "lote inválido" como erro dedicado.',
    dependeDe: ['EXPLODIRLOTE'],
    condicao: (v) => v['EXPLODIRLOTE'] === 'S',
  },
  {
    nome: 'IGNORACONTROLELOTE',
    label: 'Ignorar controle do tipo lote',
    aba: 'geral',
    subSecao: 'Produtos controlados por lote',
    controle: 'toggle',
    descricao: 'Ignora controle de lote durante a conferência.',
    status: 'parcial',
    statusObservacao: 'Quando TIPCONTEST != "L" sem LISCONTEST, o item vira SEM_CONTROLE e o campo é travado (identificarProduto) — efeito parecido, mas não vem dessa config do TGFCCO.',
  },

  // ─── Aba Geral — Peso/Balança ────────────────────────────────────────────
  {
    nome: 'REGPESOTOTAL',
    label: 'Registrar peso',
    aba: 'geral',
    subSecao: 'Peso/Balança',
    controle: 'select',
    opcoes: [
      { valor: 'N', label: 'Não Registrar' },
      { valor: 'M', label: 'Manualmente' },
      { valor: 'AM', label: 'Balança/Manual' },
      { valor: 'A', label: 'Pela balança' },
    ],
    descricao: 'Define a obrigatoriedade e origem do registro de peso do item conferido.',
    status: 'nao_implementado',
    statusObservacao: 'Nenhum campo de peso existe em SeparacaoTables.kt/DTOs.',
  },
  {
    nome: 'OBTERQTDBALANCA',
    label: 'Obter quantidade pela balança',
    aba: 'geral',
    subSecao: 'Peso/Balança',
    controle: 'select',
    opcoes: [
      { valor: 'N', label: 'Não obter' },
      { valor: 'B', label: 'Pela balança' },
      { valor: 'S', label: 'Balança/Manual' },
    ],
    descricao: 'Define se a quantidade conferida é obtida da balança (produtos vendidos por peso).',
    status: 'nao_implementado',
    statusObservacao: 'Comentário explícito em SeparacaoService.kt: "UMAs de peso continuam de fora por ora — não fazem parte do que foi pedido."',
  },

  // ─── Aba Geral — Recontagem ───────────────────────────────────────────────
  {
    nome: 'EXIBIRPRODDIVER',
    label: 'Exibir produtos divergentes na recontagem',
    aba: 'geral',
    subSecao: 'Recontagem',
    controle: 'toggle',
    descricao: 'Mostra os itens com divergência já destacados ao iniciar uma recontagem.',
    status: 'implementado',
    statusObservacao: 'Itens com scanned > expected viram status "critical" (isCritico) e são priorizados em sortedConferred.',
  },
  {
    nome: 'TIPORECONTAGEM',
    label: 'Recontagem',
    aba: 'geral',
    subSecao: 'Recontagem',
    controle: 'select',
    opcoes: [
      { valor: 'A', label: 'Automática' },
      { valor: 'C', label: 'Comandada' },
    ],
    descricao: 'Automática: botão de recontagem aparece direto ao divergir. Comandada: precisa acionar manualmente.',
    status: 'nao_implementado',
    statusObservacao: 'Não há fluxo de recontagem — só devolverItem (zera tudo), sem contagem simples/dupla.',
  },
  {
    nome: 'ABRANGRECONTAGEM',
    label: 'Abrangência da recontagem',
    aba: 'geral',
    subSecao: 'Recontagem',
    controle: 'select',
    opcoes: [
      { valor: 'S', label: 'Recontar seletivamente' },
      { valor: 'T', label: 'Recontar todos os itens' },
    ],
    descricao: 'Seletiva: reconta só os itens divergentes. Todos: reconta o documento inteiro.',
    status: 'nao_implementado',
    statusObservacao: 'Sem escopo de recontagem implementado (não existe recontagem em si).',
  },

  // ─── Aba Corte/Divergência ────────────────────────────────────────────────
  {
    nome: 'CORTECONF',
    label: 'Corte/divergência',
    aba: 'corte',
    subSecao: 'Geral',
    controle: 'select',
    opcoes: [
      { valor: 'N', label: 'Proibido' },
      { valor: 'S', label: 'Permitido' },
    ],
    descricao: 'Permite ou não cortar itens divergentes ao finalizar a conferência.',
    status: 'nao_implementado',
    statusObservacao: 'Não há conceito de "corte" (remoção parcial de item da nota) em nenhuma camada.',
  },
  {
    nome: 'QTDAMAIOR',
    label: 'Quantidade a maior',
    aba: 'corte',
    subSecao: 'Geral',
    controle: 'select',
    opcoes: [
      { valor: 'C', label: 'Proibido' },
      { valor: 'D', label: 'Permitido' },
    ],
    descricao: 'Permitido: aceita bipar mais que o negociado (finaliza divergente). Proibido: bloqueia a bipagem além do negociado.',
    status: 'parcial',
    statusObservacao: 'Divergência "a maior" é detectada e marcada critical (onConferido em conferencia.component.ts), mas sem ação configurável (permitir/bloquear) vinda do TGFCCO — hardcoded.',
  },
  {
    nome: 'QTDMINRECONT',
    label: 'Recontagens p/ permitir corte/divergência',
    aba: 'corte',
    subSecao: 'Geral',
    controle: 'numero',
    descricao: 'Quantidade de recontagens até o sistema forçar recontagem automática mesmo com corte permitido.',
    status: 'nao_implementado',
    statusObservacao: 'Sem lógica de quantidade mínima de recontagens (recontagem em si não existe).',
  },
  {
    nome: 'GERARPEDCOMPL',
    label: 'Procedimento de divergência a maior',
    aba: 'corte',
    subSecao: 'Divergência a maior',
    controle: 'select',
    opcoes: [
      { valor: 'S', label: 'Gerar ped. complementar' },
      { valor: 'A', label: 'Atualizar a quantidade negociada' },
      { valor: 'N', label: 'Não ajustar' },
    ],
    descricao: 'Define o que fazer quando a quantidade conferida excede a negociada.',
    status: 'nao_implementado',
    statusObservacao: 'Nenhuma geração de pedido complementar em qualquer camada do backend.',
  },
  {
    nome: 'MODNOTAPEDCOMPL',
    label: 'Modelo nota p/ pedido complementar',
    aba: 'corte',
    subSecao: 'Divergência a maior',
    controle: 'texto',
    descricao: 'Modelo de nota usado ao gerar pedido complementar.',
    status: 'nao_aplicavel',
    statusObservacao: 'Depende de GERARPEDCOMPL, que não existe.',
    dependeDe: ['GERARPEDCOMPL'],
    condicao: (v) => v['GERARPEDCOMPL'] === 'S',
  },
  {
    nome: 'PEDCOMPLCONFIRMADO',
    label: 'Ped. complementar confirmado',
    aba: 'corte',
    subSecao: 'Divergência a maior',
    controle: 'toggle',
    descricao: 'Define se o pedido complementar gerado já nasce confirmado.',
    status: 'nao_aplicavel',
    statusObservacao: 'Mesma dependência de GERARPEDCOMPL, inexistente.',
    dependeDe: ['GERARPEDCOMPL'],
    condicao: (v) => v['GERARPEDCOMPL'] === 'S',
  },
  {
    nome: 'PRODUTOSFORAPED',
    label: 'Produtos não constantes no pedido',
    aba: 'corte',
    subSecao: 'Divergência a maior',
    controle: 'select',
    opcoes: [
      { valor: 'C', label: 'Proibido' },
      { valor: 'D', label: 'Permitido' },
      { valor: 'X', label: 'Proibido e Exige Revisão' },
    ],
    descricao: 'Trata bipagem de produto que não está no documento original.',
    status: 'nao_implementado',
    statusObservacao: 'identificarProduto só resolve contra itens já carregados da nota; produto fora dela cai em "não encontrado" (onNaoEncontrado), sem tratamento dedicado.',
  },
  {
    nome: 'PROCEDCORTE',
    label: 'Procedimento de corte',
    aba: 'corte',
    subSecao: 'Divergência a menor',
    controle: 'select',
    opcoes: [
      { valor: 'A', label: 'Atualizar a quantidade negociada' },
      { valor: 'I', label: 'Atualizar a quantidade cortada' },
      { valor: 'G', label: 'Gerar nota de devolução' },
    ],
    descricao: 'Define como tratar a diferença quando confere-se menos do que o negociado.',
    status: 'nao_implementado',
    statusObservacao: 'Sem qualquer procedimento de corte implementado.',
  },
  {
    nome: 'CORTEPARCIAL',
    label: 'Corte parcial de itens',
    aba: 'corte',
    subSecao: 'Divergência a menor',
    controle: 'select',
    opcoes: [
      { valor: 'N', label: 'Proibido' },
      { valor: 'S', label: 'Permitido' },
    ],
    descricao: 'Permite ou não cortar apenas parte da quantidade de um item.',
    status: 'nao_implementado',
    statusObservacao: 'Idem — sem lógica de corte.',
  },
  {
    nome: 'MODNOTADEVOLUCAO',
    label: 'Modelo nota p/ devolução',
    aba: 'corte',
    subSecao: 'Divergência a menor',
    controle: 'texto',
    descricao: 'Modelo de nota usado ao gerar devolução.',
    status: 'nao_aplicavel',
    statusObservacao: 'Nenhuma geração de nota de devolução existe em wms.',
    dependeDe: ['PROCEDCORTE'],
    condicao: (v) => v['PROCEDCORTE'] === 'G',
  },
  {
    nome: 'NOTADEVCONFIRMADA',
    label: 'Nota de devolução confirmada',
    aba: 'corte',
    subSecao: 'Divergência a menor',
    controle: 'toggle',
    descricao: 'Define se a nota de devolução gerada já nasce confirmada.',
    status: 'nao_aplicavel',
    statusObservacao: 'Mesma razão — sem geração de nota de devolução.',
    dependeDe: ['PROCEDCORTE'],
    condicao: (v) => v['PROCEDCORTE'] === 'G',
  },
  {
    nome: 'LIBCORTE',
    label: 'Liberação p/ corte/divergência',
    aba: 'corte',
    subSecao: 'Divergência a menor',
    controle: 'select',
    opcoes: [
      { valor: 'N', label: 'Nunca exigir' },
      { valor: 'E', label: 'Exigir sempre' },
    ],
    descricao: 'Define se o corte exige liberação de limite.',
    status: 'nao_implementado',
    statusObservacao: 'Sem fluxo de liberação de corte/limite implementado.',
  },
  {
    nome: 'TIPOLIBERACAO',
    label: 'Tipo de liberação',
    aba: 'corte',
    subSecao: 'Divergência a menor',
    controle: 'select',
    opcoes: [
      { valor: 'D', label: 'Uma liberação por item divergente' },
      { valor: 'P', label: 'Uma liberação única por pedido' },
    ],
    descricao: 'Granularidade da liberação de limite exigida.',
    status: 'nao_implementado',
    statusObservacao: 'Sem qualquer tela/lógica de liberação (limite de crédito etc.).',
    dependeDe: ['LIBCORTE'],
    condicao: (v) => v['LIBCORTE'] === 'E',
  },
  {
    nome: 'AOLIBERAR',
    label: 'Ao liberar',
    aba: 'corte',
    subSecao: 'Divergência a menor',
    controle: 'select',
    opcoes: [
      { valor: 'M', label: 'Marcar para recontagem' },
      { valor: 'R', label: 'Reprocessar conferência' },
    ],
    descricao: 'Ação tomada após a liberação de limite ser concedida.',
    status: 'nao_implementado',
    statusObservacao: 'Idem — nenhuma ação pós-liberação implementada.',
    dependeDe: ['LIBCORTE'],
    condicao: (v) => v['LIBCORTE'] === 'E',
  },

  // ─── Aba Formação de Volumes ──────────────────────────────────────────────
  {
    nome: 'FORMACAOVOLUMES',
    label: 'Formação de volumes',
    aba: 'volumes',
    subSecao: 'Geral',
    controle: 'select',
    opcoes: [
      { valor: 'N', label: 'Não usa formação de volumes' },
      { valor: 'S', label: 'Registro simplificado (no final)' },
      { valor: 'T', label: 'Registro simplificado (na tela)' },
      { valor: 'D', label: 'Registro detalhado de volumes' },
    ],
    descricao: 'Define o nível de controle de volumes/cubagem da conferência. "Detalhado" é pré-requisito para etiqueta.',
    status: 'parcial',
    statusObservacao: 'Campo lido e cacheado (ConfigConferenciaCache.formacaoVolumes), mas nunca consumido em nenhuma lógica de negócio — sem gestão de volumes/cubagem.',
  },
  {
    nome: 'APRESFILASEMPRE',
    label: 'Sempre apresentar na fila de conferência',
    aba: 'volumes',
    subSecao: 'Geral',
    controle: 'toggle',
    descricao: 'Documento aparece na Fila de Conferência mesmo sem nenhum produto conferível.',
    status: 'nao_implementado',
    statusObservacao: 'fila-tarefas.component.ts/ConferenciasService.listarFila não tem essa regra — filtros são só por status/busca local.',
  },
  {
    nome: 'IMPDANFEVOL',
    label: 'Imprimir um DANFE por volume',
    aba: 'volumes',
    subSecao: 'Geral',
    controle: 'toggle',
    descricao: 'Imprime uma DANFE para cada volume formado.',
    status: 'nao_aplicavel',
    statusObservacao: 'Nenhuma impressão de DANFE/volume existe no projeto.',
  },
  {
    nome: 'IMPREETIQUETAS',
    label: 'Imprimir etiquetas ao finalizar conferência',
    aba: 'volumes',
    subSecao: 'Geral',
    controle: 'toggle',
    descricao: 'Dispara impressão de etiqueta ao concluir a conferência.',
    status: 'nao_aplicavel',
    statusObservacao: 'Nenhuma impressão de etiqueta existe no projeto.',
    dependeDe: ['FORMACAOVOLUMES'],
    condicao: (v) => v['FORMACAOVOLUMES'] === 'D',
  },
  {
    nome: 'IMPETIQVOL',
    label: 'Imprimir uma etiqueta por volume',
    aba: 'volumes',
    subSecao: 'Geral',
    controle: 'toggle',
    descricao: 'Para conferências com 2+ volumes, imprime uma etiqueta por volume.',
    status: 'nao_aplicavel',
    statusObservacao: 'Mesma razão — sem impressão de etiqueta.',
    dependeDe: ['FORMACAOVOLUMES'],
    condicao: (v) => v['FORMACAOVOLUMES'] === 'D',
  },
  {
    nome: 'NURFEETIQ',
    label: 'Modelo p/ etiqueta',
    aba: 'volumes',
    subSecao: 'Geral',
    controle: 'texto',
    descricao: 'Modelo de relatório usado na impressão da etiqueta.',
    status: 'nao_aplicavel',
    statusObservacao: 'Depende de impressão de etiquetas, inexistente.',
    dependeDe: ['FORMACAOVOLUMES'],
    condicao: (v) => v['FORMACAOVOLUMES'] === 'D',
  },
  {
    nome: 'NUETIQPESO',
    label: 'Modelo p/ etiqueta (peso)',
    aba: 'volumes',
    subSecao: 'Geral',
    controle: 'texto',
    descricao: 'Modelo de relatório usado na impressão da etiqueta por peso.',
    status: 'nao_aplicavel',
    statusObservacao: 'Mesma razão.',
    dependeDe: ['FORMACAOVOLUMES'],
    condicao: (v) => v['FORMACAOVOLUMES'] === 'D',
  },
];

export const ABAS: { valor: 'geral' | 'corte' | 'volumes'; label: string }[] = [
  { valor: 'geral', label: 'Geral' },
  { valor: 'corte', label: 'Corte/Divergência' },
  { valor: 'volumes', label: 'Formação de Volumes' },
];
