package wms.backend.mapaseparacao

import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.sync.Semaphore
import kotlinx.coroutines.sync.withPermit
import kotlinx.serialization.Serializable
import wms.backend.erp.SankhyaDbExplorerClient

/**
 * Pedido de Venda (porte do relatório Jasper PEDIDO_VENDA_NEGRI_UNICO_V8.jrxml) — impresso junto do Mapa de
 * Separação, um por Nº Único. A SQL é a MESMA do relatório (copiada do .jrxml; parâmetros: NUNOTA e
 * MOSTRAR_COMISSAO=1, o padrão dele). Uma linha por item ('I'), parcela ('F') e comissão ('C'), com o
 * cabeçalho (C.*) e os totais (T.*) repetidos em toda linha — separados aqui. Valores vêm como texto do
 * DbExplorer (números com ponto, datas "ddMMyyyy HH:mm:ss"); o frontend formata.
 */
@Serializable
data class PedidoVendaDto(
    val nunota: Long,
    /** Campos de cabeçalho e totais (nomes das colunas da SQL: NUMNOTA, RAZAOEMP, TOTAL_PRODUTO, ...). */
    val cabecalho: Map<String, String?> = emptyMap(),
    val itens: List<Map<String, String?>> = emptyList(),
    val parcelas: List<Map<String, String?>> = emptyList(),
    val comissoes: List<Map<String, String?>> = emptyList(),
    /** Pedido não encontrado ou falha na consulta — o mapa imprime sem ele. */
    val erro: String? = null,
)

object PedidoVendaService {
    private const val CONCORRENCIA = 4

    private val CAMPOS_CABECALHO = listOf(
        "NUNOTA", "NUMNOTA", "ORDEMCARGA", "DTNEG", "DTPREVENT", "CODPARC", "CODVEND", "PESOBRUTO", "QTDVOL",
        "VLRNOTA", "VLRFRETE", "VLRDESCTOT", "OBSERVACAO", "RAZAOEMP", "EMP_CGC", "EMP_TELEFONE", "EMP_ENDERECO",
        "EMP_BAIRRO", "EMP_CIDADE", "EMP_UF", "EMP_CEP", "APELIDO", "NOMEPARC", "RAZAOSOCIAL", "TELEFONE", "CGC_CPF",
        "CEP", "INSCESTADNAUF", "ENDERECO", "NOMECID", "UF", "NOMEBAI", "CONTATO", "TELCONTATO", "TRANSPORTADORA",
        "CONDICAO", "TOTAL_PRODUTO", "TOTAL_SERVICO", "TOTAL_DESCONTO", "TOTAL_LIQUIDO", "TOTAL_IPI", "TOTAL_ST",
    )

    suspend fun buscar(tenantSlug: String, nunotas: List<Long>): List<PedidoVendaDto> = coroutineScope {
        val semaforo = Semaphore(CONCORRENCIA)
        nunotas.distinct().map { n -> async { semaforo.withPermit { buscarUm(tenantSlug, n) } } }.awaitAll()
    }

    private suspend fun buscarUm(tenantSlug: String, nunota: Long): PedidoVendaDto {
        val linhas = runCatching { SankhyaDbExplorerClient.executarQuery(tenantSlug, SQL.replace("__NUNOTA__", nunota.toString())) }
            .getOrElse { return PedidoVendaDto(nunota, erro = "falha ao consultar o pedido $nunota: ${it.message}") }
        val primeira = linhas.firstOrNull() ?: return PedidoVendaDto(nunota, erro = "pedido $nunota não encontrado")
        return PedidoVendaDto(
            nunota = nunota,
            cabecalho = CAMPOS_CABECALHO.associateWith { primeira[it] },
            itens = linhas.filter { it["TIPO"] == "I" && !it["CODPROD"].isNullOrBlank() },
            parcelas = linhas.filter { it["TIPO"] == "F" },
            comissoes = linhas.filter { it["TIPO"] == "C" },
        )
    }

    /** SQL do PEDIDO_VENDA_NEGRI_UNICO_V8.jrxml (verbatim; __NUNOTA__ = NUNOTA do relatório, MOSTRAR_COMISSAO = 1). */
    private val SQL = """
WITH C AS (
 SELECT CAB.NUNOTA,CAB.NUMNOTA,CAB.ORDEMCARGA,CAB.DTNEG,CAB.DTPREVENT,
 CAB.CODPARC,CAB.CODVEND,NVL(CAB.PESOBRUTO,0) PESOBRUTO,CAB.QTDVOL,
 NVL(CAB.VLRNOTA,0) VLRNOTA,NVL(CAB.VLRFRETE,0) VLRFRETE,NVL(CAB.VLRDESCTOT,0) VLRDESCTOT,
 CAB.OBSERVACAO,EMP.RAZAOSOCIAL RAZAOEMP,EMP.CGC EMP_CGC,EMP.TELEFONE EMP_TELEFONE,
 NVL(EE.TIPO || ' ','') || NVL(EE.NOMEEND,'') || CASE WHEN EMP.NUMEND IS NOT NULL THEN ', ' || EMP.NUMEND END EMP_ENDERECO,
 EB.NOMEBAI EMP_BAIRRO,EC.NOMECID EMP_CIDADE,EU.UF EMP_UF,EMP.CEP EMP_CEP,
 VEN.APELIDO,PAR.NOMEPARC,PAR.RAZAOSOCIAL,PAR.TELEFONE,PAR.CGC_CPF,PAR.CEP,PAR.INSCESTADNAUF,
 NVL(ENDE.TIPO || ' ','') || NVL(ENDE.NOMEEND,'') || CASE WHEN PAR.NUMEND IS NOT NULL THEN ', ' || PAR.NUMEND END || CASE WHEN PAR.COMPLEMENTO IS NOT NULL THEN ' - ' || PAR.COMPLEMENTO END ENDERECO,
 CID.NOMECID,UFS.UF,BAI.NOMEBAI,CTT.NOMECONTATO CONTATO,CTT.TELEFONE TELCONTATO,
 TRA.NOMEPARC TRANSPORTADORA,TPV.DESCRTIPVENDA CONDICAO
 FROM TGFCAB CAB
 JOIN TSIEMP EMP ON EMP.CODEMP=CAB.CODEMP
 JOIN TGFPAR PAR ON PAR.CODPARC=CAB.CODPARC
 LEFT JOIN TSIEND EE ON EE.CODEND=EMP.CODEND
 LEFT JOIN TSIBAI EB ON EB.CODBAI=EMP.CODBAI
 LEFT JOIN TSICID EC ON EC.CODCID=EMP.CODCID
 LEFT JOIN TSIUFS EU ON EU.CODUF=EC.UF
 LEFT JOIN TGFVEN VEN ON VEN.CODVEND=CAB.CODVEND
 LEFT JOIN TSIEND ENDE ON ENDE.CODEND=PAR.CODEND
 LEFT JOIN TSICID CID ON CID.CODCID=PAR.CODCID
 LEFT JOIN TSIUFS UFS ON UFS.CODUF=CID.UF
 LEFT JOIN TSIBAI BAI ON BAI.CODBAI=PAR.CODBAI
 LEFT JOIN TGFCTT CTT ON CTT.CODPARC=CAB.CODPARC AND CTT.CODCONTATO=CAB.CODCONTATO
 LEFT JOIN TGFPAR TRA ON TRA.CODPARC=CAB.CODPARCTRANSP
 LEFT JOIN TGFTPV TPV ON TPV.CODTIPVENDA=CAB.CODTIPVENDA AND TPV.DHALTER=CAB.DHTIPVENDA
 WHERE CAB.NUNOTA=__NUNOTA__
), I AS (
 SELECT ITE.SEQUENCIA,ITE.CODPROD,PRO.DESCRPROD,ITE.USOPROD,ITE.CODVOL,ITE.CONTROLE,
 CASE WHEN VOA.CODPROD IS NULL THEN ITE.QTDNEG WHEN VOA.DIVIDEMULTIPLICA='D' THEN ITE.QTDNEG*VOA.QUANTIDADE ELSE ITE.QTDNEG/NULLIF(VOA.QUANTIDADE,0) END QTDNEG,
 CASE WHEN VOA.CODPROD IS NULL THEN ITE.VLRUNIT WHEN VOA.DIVIDEMULTIPLICA='D' THEN ITE.VLRUNIT/NULLIF(VOA.QUANTIDADE,0) ELSE ITE.VLRUNIT*VOA.QUANTIDADE END VLRUNIT,
 NVL(ITE.VLRDESC,0) VLRDESC,ITE.QTDNEG*ITE.VLRUNIT TOTALITEM,
 NVL(ITE.VLRTOT,0)-NVL(ITE.VLRDESC,0) TOTLIQ,
 NVL(ITE.ALIQIPI,0) ALIQIPI,NVL(ITE.VLRIPI,0) VLRIPI,NVL(ITE.VLRSUBST,0) VLRSUBST
 FROM TGFITE ITE
 JOIN TGFPRO PRO ON PRO.CODPROD=ITE.CODPROD
 LEFT JOIN TGFVOA VOA ON VOA.CODPROD=ITE.CODPROD AND VOA.CODVOL=ITE.CODVOL
 AND ((ITE.CONTROLE IS NULL AND VOA.CONTROLE=' ') OR (ITE.CONTROLE IS NOT NULL AND ITE.CONTROLE=VOA.CONTROLE))
 WHERE ITE.NUNOTA=__NUNOTA__ AND ITE.SEQUENCIA>0
), T AS (
 SELECT NVL(SUM(CASE WHEN USOPROD='S' THEN 0 ELSE TOTALITEM END),0) TOTAL_PRODUTO,
 NVL(SUM(CASE WHEN USOPROD='S' THEN TOTALITEM ELSE 0 END),0) TOTAL_SERVICO,
 NVL(SUM(VLRDESC),0) TOTAL_DESCONTO,NVL(SUM(TOTLIQ),0) TOTAL_LIQUIDO,
 NVL(SUM(VLRIPI),0) TOTAL_IPI,NVL(SUM(VLRSUBST),0) TOTAL_ST FROM I
), R AS (
 SELECT 'I' TIPO,0 ORDEM,SEQUENCIA,CODPROD,DESCRPROD,USOPROD,CODVOL,CONTROLE,QTDNEG,VLRUNIT,TOTALITEM,TOTLIQ,VLRDESC,ALIQIPI,VLRIPI,VLRSUBST,
 VLRUNIT + VLRIPI/NULLIF(QTDNEG,0) UNIT_IPI,TOTLIQ+VLRIPI TOTAL_IPI_ITEM,
 CAST(NULL AS VARCHAR2(100)) DESDOBRAMENTO,CAST(NULL AS DATE) DTVENC,CAST(NULL AS NUMBER) VLRDESDOB,
 CAST(NULL AS NUMBER) COM_CODVEND,CAST(NULL AS VARCHAR2(100)) COM_APELIDO,CAST(NULL AS NUMBER) PERCCOM FROM I
 UNION ALL
 SELECT 'F',1,ROW_NUMBER() OVER(ORDER BY FIN.DESDOBRAMENTO,FIN.DTVENC,FIN.NUFIN),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 FIN.DESDOBRAMENTO,FIN.DTVENC,FIN.VLRDESDOB,NULL,NULL,NULL FROM TGFFIN FIN WHERE FIN.NUNOTA=__NUNOTA__
 UNION ALL
 SELECT 'C',2,ROW_NUMBER() OVER(ORDER BY CCM.CODVEND),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,CCM.CODVEND,V.APELIDO,CCM.PERCCOM FROM TGFCCM CCM
 LEFT JOIN TGFVEN V ON V.CODVEND=CCM.CODVEND
 WHERE CCM.NUNOTA=__NUNOTA__ AND 1=1
 UNION ALL
 SELECT 'I',0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM I)
)
SELECT C.*,T.*,R.TIPO,R.SEQUENCIA,R.CODPROD,R.DESCRPROD,R.USOPROD,R.CODVOL,R.CONTROLE,(SELECT PRO2.COMPLDESC FROM TGFPRO PRO2 WHERE PRO2.CODPROD=R.CODPROD) COMPLDESC,R.QTDNEG,R.VLRUNIT,R.TOTALITEM,R.TOTLIQ,R.VLRDESC,R.ALIQIPI,R.VLRIPI,R.VLRSUBST,R.UNIT_IPI,R.TOTAL_IPI_ITEM,R.DESDOBRAMENTO,R.DTVENC,R.VLRDESDOB,R.COM_CODVEND,R.COM_APELIDO,R.PERCCOM
FROM C CROSS JOIN T CROSS JOIN R ORDER BY R.ORDEM,R.SEQUENCIA
""".trimIndent()
}
